import { allFields, type Answers } from "@/lib/intake-definition";

const monthCodes: Record<string, string> = {
  JAN: "01",
  FEB: "02",
  MAR: "03",
  APR: "04",
  MAY: "05",
  JUN: "06",
  JUL: "07",
  AUG: "08",
  SEP: "09",
  OCT: "10",
  NOV: "11",
  DEC: "12",
};

function dateFromParts(day: string, month: string, year: string) {
  const normalizedMonth = monthCodes[month.toUpperCase()] ?? month;
  return `${year}-${normalizedMonth.padStart(2, "0")}-${day.padStart(2, "0")}`;
}

/** Mirrors the MVP frontend's createDefaultApplication sample as flat intake answers. */
export function createLocalhostPrefillAnswers(): Answers {
  const answers: Answers = {
    "meta.locationCode": "HYD",
    "meta.securityAnswer": "TestAnswer",
    "personalInformation1.surname": "TEST",
    "personalInformation1.givenNames": "APPLICANT",
    "personalInformation1.fullNameNativeAlphabetDoesNotApply": true,
    "personalInformation1.otherNamesUsed": "NO",
    "personalInformation1.telecodeNameUsed": "NO",
    "personalInformation1.sex": "M",
    "personalInformation1.maritalStatus": "S",
    "personalInformation1.dateOfBirth": dateFromParts("01", "JAN", "1990"),
    "personalInformation1.cityOfBirth": "HYDERABAD",
    "personalInformation1.stateProvinceOfBirth": "TELANGANA",
    "personalInformation1.countryRegionOfBirth": "IND",
    "personalInformation2.nationality": "IND",
    "personalInformation2.hasOtherNationality": "NO",
    "personalInformation2.isPermanentResidentOfOtherCountry": "NO",
    "personalInformation2.nationalIdentificationNumberDoesNotApply": true,
    "personalInformation2.hasSSN": "NO",
    "personalInformation2.hasTaxpayerID": "NO",
    "passport.passportType": "R",
    "passport.passportNumber": "X1234567",
    "passport.issuedCountry": "IND",
    "passport.issuedCity": "HYDERABAD",
    "passport.issuedState": "TELANGANA",
    "passport.issuedInCountry": "IND",
    "passport.issuedDate": dateFromParts("01", "01", "2020"),
    "passport.expirationDate": dateFromParts("01", "01", "2030"),
    "passport.lostStolen": "NO",
    "travelInformation.purposeOfTrip": "B",
    "travelInformation.otherPurpose": "B1-B2",
    "travelInformation.hasSpecificTravelPlans": "NO",
    "travelInformation.arrivalDate": dateFromParts("15", "12", "2026"),
    "travelInformation.lengthOfStay.duration": "14",
    "travelInformation.lengthOfStay.unit": "D",
    "travelInformation.locationsToVisit": "New York",
    "travelInformation.usAddress.street": "123 Main Street",
    "travelInformation.usAddress.city": "New York",
    "travelInformation.usAddress.state": "NY",
    "travelInformation.usAddress.zipCode": "10001",
    "travelInformation.payingForTrip": "S",
    "travelCompanions.otherPersonsTravelingWithYou": "NO",
    "previousUsTravel.beenToUs": "NO",
    "previousUsTravel.visaIssued": "NO",
    "previousUsTravel.visaRefused": "NO",
    "previousUsTravel.immigrantPetition": "NO",
    "addressPhone.street": "123 TEST STREET",
    "addressPhone.city": "HYDERABAD",
    "addressPhone.state": "TELANGANA",
    "addressPhone.postalCode": "500001",
    "addressPhone.country": "IND",
    "addressPhone.mailingSameAsHome": "YES",
    "addressPhone.primaryPhone": "9876543210",
    "addressPhone.email": "test.applicant@example.com",
    "addressPhone.additionalPhone": "NO",
    "addressPhone.additionalEmail": "NO",
    "addressPhone.socialMedia": "NO",
    "usContact.nameDoesNotApply": false,
    "usContact.surname": "CONTACT",
    "usContact.givenNames": "TEST",
    "usContact.organization": "TEST HOTEL",
    "usContact.relationship": "C",
    "usContact.street": "123 MAIN STREET",
    "usContact.city": "NEW YORK",
    "usContact.state": "NY",
    "usContact.postalCode": "10001",
    "usContact.phone": "2125550100",
    "usContact.email": "us.contact@example.com",
    "family.fatherSurnameUnknown": false,
    "family.fatherSurname": "FATHER",
    "family.fatherGivenNamesUnknown": false,
    "family.fatherGivenNames": "TEST",
    "family.fatherDobUnknown": false,
    "family.fatherDateOfBirth": dateFromParts("01", "JAN", "1960"),
    "family.fatherLiveInUs": "NO",
    "family.motherSurnameUnknown": false,
    "family.motherSurname": "MOTHER",
    "family.motherGivenNamesUnknown": false,
    "family.motherGivenNames": "TEST",
    "family.motherDobUnknown": false,
    "family.motherDateOfBirth": dateFromParts("01", "JAN", "1962"),
    "family.motherLiveInUs": "NO",
    "family.immediateUsRelative": "NO",
    "family.otherUsRelative": "NO",
    "workEducation.occupation": "N",
    "workEducation.notEmployedExplain": "STUDENT",
    "workEducation.employerName": "TEST SCHOOL",
    "workEducation.jobTitle": "STUDENT",
    "workEducation.employerStreet": "123 CAMPUS ROAD",
    "workEducation.employerCity": "HYDERABAD",
    "workEducation.employerState": "TELANGANA",
    "workEducation.employerPostalCode": "500001",
    "workEducation.employerCountry": "IND",
    "workEducation.employerPhone": "9876543210",
    "workEducation.startDate": dateFromParts("01", "06", "2024"),
    "workEducation.monthlyIncome": "0",
    "workEducation.duties": "Student coursework and study.",
    "previousWorkEducation.previouslyEmployed": "NO",
    "previousWorkEducation.otherEducation": "NO",
    "additionalWorkEducation.clanOrTribe": "NO",
    "additionalWorkEducation.languages": "ENGLISH",
    "additionalWorkEducation.countriesVisited": "NO",
    "additionalWorkEducation.organization": "NO",
    "additionalWorkEducation.specializedSkills": "NO",
    "additionalWorkEducation.militaryService": "NO",
    "additionalWorkEducation.insurgentOrg": "NO",
  };

  for (const field of allFields) {
    if (field.id.startsWith("security.") && field.kind === "yesno") {
      answers[field.id] = "NO";
    }
  }

  return answers;
}
